version: '3.6'
services:
  plugin:
    build: ./
    volumes:
      - ./:/code
    environment:
      MONGO_URI: mongodb://mongodb:27017/mongooseLeanDefaults
  mongodb:
    image: mongo:latest
    logging:
      driver: none
