name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        node: ['16', '18', '20', '22']
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    name: Install Dependencies & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  publish-npm:
    name: Publish to NPM
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
