name: Run Tests

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      matrix:
        node: ['12', '14', '16', '18']
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
